name: inc
description: An inline pattern compiler for embedding code into static files.
version: 1.0.5
repository: https://github.com/tytydraco/inc

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  args: ^2.3.1
  io: ^1.0.3

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: ^3.0.1

executables:
  inc: inc
